### PR TITLE
Fix the span names generated from HTTP requests

### LINKED ISSUE #335: plugin/http/httptrace: do not replace req.URL.Scheme unless it is set
httptrace_test.go:231: invalid name: Recv./.e.x.a.m.p.l.e./.u.r.l./.p.a.t.h.?.q.p.a.r.a.m.=.v.a.l.
	httptrace_test.go:226: invalid name: Sent.://127.0.0.1:59761/example/url/path?qparam=val

### PR DESCRIPTION
**Pull request by rakyll**
Handle cases where there is no hostname and port name.
Avoid putting :80 and :443 in the span name.

Fixes #335.

### CODE REVIEW

File: plugin/http/httptrace/httptrace.go [hunk 1]
```diff
@@ -189,3 +189,12 @@ func (h *handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
 	h.handler.ServeHTTP(w, r)
 }
+
+func spanNameFromURL(prefix string, u *url.URL) string {
+	host := u.Hostname()
+	port := ":" + u.Port()
+	if port == ":" || port == ":80" || port == ":443" {
+		port = ""
+	}
+	return prefix + "." + host + port + u.Path
```
Comment (odeke-em) [inline plugin/http/httptrace/httptrace.go]: How come we are no longer including the query string in here?

Comment (yurishkuro) [reply plugin/http/httptrace/httptrace.go]: query string can be very high cardinality, like `?userId={uuid}`. But then the `Path` could contain UUIDs as well, is it a good idea to include it in the span name?

Comment (ramonza) [reply plugin/http/httptrace/httptrace.go]: I agree with the removal of the query string. I view the Span name as something that should be "static", akin to Tag/Measure/View names.

Comment (ramonza) [reply plugin/http/httptrace/httptrace.go]: If we need the query string, it could be added as a annotation to the Span.

File: plugin/http/httptrace/httptrace_test.go [hunk 2]
```diff
@@ -273,3 +275,38 @@ func serveHTTP(done chan struct{}, wait chan time.Time) string {
...
+		want   string
+	}{
+		{
+			prefix: "Sent",
+			u:      "http://localhost:80/hello?q=a",
+			want:   "Sent.localhost/hello",
+		},
+		{
+			prefix: "Recv",
+			u:      "https://localhost:443/a",
```
Comment (ramonza) [inline plugin/http/httptrace/httptrace_test.go]: Could you add an example with a non-standard port?

Comment (rakyll) [reply plugin/http/httptrace/httptrace_test.go]: Path will be represented as an attributed. Added a case for a non-standard port. PTAL.
