### PR TITLE
made trackingResponseWriter a properly transparent wrapper

### LINKED ISSUE #744: plugin/ochttp: implement io.ReadFrom
https://github.com/census-instrumentation/opencensus-go/issues/642 was opened to implement the hijacker interface for websocket support. 
Beside Hijacker and Flusher the default implementation of `http.ResponseWriter` supports a few other additional "upgradable" interfaces. When these are not implemented in middleware it can lead to subtle bugs and performance regressions in proxies that use the http plugin. 

https://avtok.com/2014/11/05/interface-upgrades.html
https://github.com/felixge/httpsnoop#why-this-package-exists

Popular middleware packages like https://github.com/gorilla/handlers and [chi](https://github.com/go-chi/chi) implement the entire subset of these methods. It looks like the ochttp plugin only supports Hijack and Flush today, leaving `CloseNotify`, `Push`, and `ReadFrom`.

### PR DESCRIPTION
**Pull request by basvanbeek**
The trackingResponseWriter used by ochttp implemented most of the additional interfaces that can be found in http ResponseWriter implementations by wrapping the involved methods. It lacked the io.ReaderFrom additional interface.

The downside of wrapping all potential methods per these interfaces is that code testing for the availability of these interfaces can signal false positives when the underlying implementation does not support them allowing for changed behavior.

This PR solves the problem of false positives by only embedding the interfaces found in the underlying implementation, making trackingResponseWriter completely transparent to its consumers. It also includes handling of io.ReaderFrom which fixes #744.

### CODE REVIEW

File: plugin/ochttp/server.go [hunk 1]
```diff
@@ -223,8 +191,231 @@ func (t *trackingResponseWriter) WriteHeader(statusCode int) {
...
 }
 
-func (t *trackingResponseWriter) Flush() {
-	if flusher, ok := t.writer.(http.Flusher); ok {
-		flusher.Flush()
+// wrappedResponseWriter returns a wrapped version of the original
+//  ResponseWriter and only implements the same combination of additional
+// interfaces as the original.
+// This implementation is based on https://github.com/felixge/httpsnoop.
+func (t *trackingResponseWriter) wrappedResponseWriter() http.ResponseWriter {
```
Comment (ramonza) [inline plugin/ochttp/server.go]: Is this code generated? It would be great to get the script used committed as well. I can imagine this being useful for databases/sql stuff as well.

File: plugin/ochttp/server.go [hunk 2]
```diff
@@ -153,39 +151,9 @@ type trackingResponseWriter struct {
 	writer     http.ResponseWriter
 }
 
-// Compile time assertions for widely used net/http interfaces
-var _ http.CloseNotifier = (*trackingResponseWriter)(nil)
-var _ http.Flusher = (*trackingResponseWriter)(nil)
-var _ http.Hijacker = (*trackingResponseWriter)(nil)
-var _ http.Pusher = (*trackingResponseWriter)(nil)
+// Compile time assertion for ResponseWriter interface
```
Comment (ramonza) [inline plugin/ochttp/server.go]: I get that it's not possible to test this with a static assertion any longer but would it be possible to test with reflection?

File: plugin/ochttp/server.go (hunk 1 above)
Comment (basvanbeek) [reply plugin/ochttp/server.go]: It wasn't generated, but it could be. I might build a generic generator for optional interfaces as I have some ideas about it. database/sql doesn't have many optional interfaces that need to be wrapped like this. Most of the optional interfaces allow the method implementations to return `driver.ErrSkip` to signal the fast path / implementation is unavailable so I only had to use this logic for `driver.StmtExecContext` and `driver.StmtQueryContext`

File: plugin/ochttp/server.go (hunk 2 above)
Comment (basvanbeek) [reply plugin/ochttp/server.go]: Feels like a who tests the tester kind of scenario. I think it makes more sense to test for actual scenarios (which we already have a few in) then some synthetic catch all test.

File: plugin/ochttp/server.go (hunk 1 above)
Comment (ramonza) [reply plugin/ochttp/server.go]: ack

**Comment by ramonza** [comment]
LGTM
