### PR TITLE
Fix Aggregation types for Views in plugin/grpc/grpcstats

### LINKED ISSUE #210: plugin/grpc/grpcstats: views should be consistent with the Java views
There are some inconsistencies in the views we are providing from the grpcstats package with what Java provides.

For example, grpc.io/client/error_count/cumulative is a mean aggregation in Java, a count aggregation in Go.

Use https://github.com/census-instrumentation/opencensus-java/blob/master/contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java as a reference to find out the mismatching cases and fix them.

### PR DESCRIPTION
**Pull request by odeke-em**
Fix up the aggregation types for the various stats.Views
in plugin/grpc/grpcstats to ensure they conform to those
from the reference Java implementation as per
https://github.com/census-instrumentation/opencensus-java/blob/2b464864e3dd3f80e8e4c9dc72fccc225444a939/contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java#L113-L658

Also added a test that at runtime ensures that the types match
up what we expect lest we get errors such as

```shell
=== RUN   TestViewsAggregationsConform
--- FAIL: TestViewsAggregationsConform (0.00s)
  client_metrics_test.go:33: Item on line: 40 got stats.DistributionAggregation want stats.MeanAggregation
  client_metrics_test.go:33: Item on line: 41 got stats.DistributionAggregation want stats.MeanAggregation
  client_metrics_test.go:33: Item on line: 42 got stats.DistributionAggregation want stats.MeanAggregation
FAIL
exit status 1
FAIL  go.opencensus.io/plugin/grpc/grpcstats  0.011s
```

Fixes #210

### CODE REVIEW

**Comment by odeke-em** [comment]
Cool, thanks for the reviews y'all.

File: plugin/grpc/grpcstats/client_metrics.go [hunk 1]
```diff
@@ -97,7 +97,9 @@ func defaultClientMeasures() {
 }
 
 func defaultClientViews() {
-	RPCClientErrorCountView, _ = stats.NewView("grpc.io/client/error_count/cumulative", "RPC Errors", []tag.Key{keyOpStatus, keyService, keyMethod}, RPCClientErrorCount, aggCount, windowCumulative)
+	// Use the Java implementation as a reference at
+	// https://github.com/census-instrumentation/opencensus-java/blob/2b464864e3dd3f80e8e4c9dc72fccc225444a939/contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java#L113-L658
+	RPCClientErrorCountView, _ = stats.NewView(" rpc.io/client/error_count/cumulative", "RPC Errors", []tag.Key{keyOpStatus, keyService, keyMethod}, RPCClientErrorCount, aggMean, windowCumulative)
```
Comment (jcd2) [inline plugin/grpc/grpcstats/client_metrics.go]: rpc.io -> grpc.io

Comment (odeke-em) [reply plugin/grpc/grpcstats/client_metrics.go]: Oops, nice catch @jcd2, I've fixed this up with https://github.com/census-instrumentation/opencensus-go/pull/225.
