### PR TITLE
Export trace attributes and annotations properly to Jaeger

### LINKED ISSUE #621: Jaeger exported traces are incomplete
I was experimenting with OpenCensus (thanks for open-sourcing this, it's a great project) and it looks like there are quite a few things I can't get working properly when exporting traces to Jaeger.
I setup a simple project where I create a span and try to add attributes, annotations and a status:
`_, span := trace.StartSpan(ctx, "dummy/api")`
`defer span.End()`

`span.AddAttributes(trace.Int64Attribute("swag", 42))`
`span.Annotate([]trace.Attribute{trace.StringAttribute("attr", "this is an attribute")}, "this is an annotation")`
`span.SetStatus(trace.Status{Code: 2, Message: "failed"})`

The traces are correctly exported to Jaeger and visible in Jaeger UI, but:

- I see the key for the Int64Attribute but the value is empty
- I see a log in the Jaeger UI which contains my 'swag' and 'attr' attributes (but swag is still empty) but it doesn't contain my annotation
- the trace status isn't taken into account

Is there something I'm doing wrong, or is it because there are inconsistencies between Jaeger's format and OpenCensus'?

### PR DESCRIPTION
**Pull request by rakyll**
Fixes #621.

### CODE REVIEW

File: exporter/jaeger/jaeger_test.go [hunk 1]
```diff
@@ -49,3 +54,75 @@ func Test_bytesToInt64(t *testing.T) {
...
+	tests := []struct {
+		name string
+		data *trace.SpanData
+		want *gen.Span
+	}{
+		{
+			name: "no parent",
+			data: &trace.SpanData{
+				SpanContext: trace.SpanContext{
+					TraceID: trace.TraceID{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16},
```
Comment (odeke-em) [inline exporter/jaeger/jaeger_test.go]: Could you make this a 16 byte TraceID to conform with the usual? This is 15 bytes and it even produces Spans that have 15 byte SpanIDs and TraceIDs.

File: exporter/jaeger/jaeger.go [hunk 2]
```diff
@@ -120,26 +120,36 @@ type Exporter struct {
...
+
 	var logs []*gen.Log
 	for _, a := range data.Annotations {
-		var fields []*gen.Tag
+		fields := make([]*gen.Tag, 0, len(a.Attributes))
 		for k, v := range a.Attributes {
 			tag := attributeToTag(k, v)
 			if tag != nil {
-				fields = append(tags, tag)
+				fields = append(fields, tag)
```
Comment (odeke-em) [inline exporter/jaeger/jaeger.go]: Great catch!

File: exporter/jaeger/jaeger_test.go (hunk 1 above)
Comment (odeke-em) [reply exporter/jaeger/jaeger_test.go]: Aha, you missed 12 in there :)

Comment (rakyll) [reply exporter/jaeger/jaeger_test.go]: Whoops, it was a mistake. Done.

Comment (odeke-em) [reply exporter/jaeger/jaeger_test.go]: That'll change the value of the TraceIDHigh, *Low, SpanID.
Let's also add tests to ensure that they TraceIDHigh is 8 bytes and same for TraceIDLow otherwise we'd never catch such discrepancies.

Comment (rakyll) [reply exporter/jaeger/jaeger_test.go]: I don't think we need a test for this. There might be trailing zeros. The trace ID was 16-bytes with a trailing zero which is still valid.

**Comment by rakyll** [comment]
@odeke-em PTAL

File: exporter/jaeger/jaeger_test.go [hunk 3]
```diff
@@ -49,3 +54,75 @@ func Test_bytesToInt64(t *testing.T) {
...
+							"answer": answerValue,
+						},
+					},
+				},
+				Status: trace.Status{Code: 2, Message: "error"},
+			},
+			want: &gen.Span{
+				TraceIdLow:    651345242494996240,
+				TraceIdHigh:   72623859790382856,
+				SpanId:        72623859790382856,
```
Comment (odeke-em) [inline exporter/jaeger/jaeger_test.go]: How is this possible?
